/**
 * マップ構文で利用する関数名です。
 */
export enum MapFunction {
  SetGauge = 'setgauge',
  SetCenter = 'setcenter',
  SetFunction = 'setfunction',
  BeginTransition = 'begintransition',
  Begin = 'begin',
  End = 'end',
  Interpolate = 'interpolate',
  Change = 'change',
  X_Interpolate = 'x.interpolate',
  Y_Interpolate = 'y.interpolate',
  Position = 'position',
  Cant_SetGauge = 'cant.setgauge',
  Cant_SetCenter = 'cant.setcenter',
  Cant_SetFunction = 'cant.setfunction',
  Cant_BeginTransition = 'cant.begintransition',
  Cant_Begin = 'cant.begin',
  Cant_End = 'cant.end',
  Cant_Interpolate = 'cant.interpolate',
  Load = 'load',
  Put = 'put',
  Put0 = 'put0',
  PutBetween = 'putbetween',
  Begin0 = 'begin0',
  SetSpeedLimit = 'setspeedlimit',
  Pass = 'pass',
  Ambient = 'ambient',
  Diffuse = 'diffuse',
  Direction = 'direction',
  Play = 'play',
  Add = 'add',
  Enable = 'enable',
  Stop = 'stop',
}
